from __future__ import annotations

import shutil
from dataclasses import dataclass
from pathlib import Path

from .config import AppConfig
from .utils import timestamp_id


BEGIN_MARKER = "-- BEGIN RE9_AESTHETIC_POSE_LOGGER"
END_MARKER = "-- END RE9_AESTHETIC_POSE_LOGGER"


@dataclass(frozen=True)
class LuaPatchStatus:
    lua_path: Path
    exists: bool
    patched: bool
    message: str


def _lua_string(value: str | Path) -> str:
    return str(value).replace("\\", "/").replace('"', '\\"')


def check_lua(config: AppConfig) -> LuaPatchStatus:
    lua_path = config.lua_path
    if not lua_path.exists():
        return LuaPatchStatus(lua_path, False, False, f"Lua file not found: {lua_path}")
    text = _read_text_preserving(lua_path)[0]
    patched = BEGIN_MARKER in text and END_MARKER in text
    return LuaPatchStatus(lua_path, True, patched, "Lua file exists.")


def backup_lua(config: AppConfig) -> Path:
    lua_path = config.lua_path
    if not lua_path.exists():
        raise FileNotFoundError(f"Lua file not found: {lua_path}")
    backup_dir = config.lua_backup_dir
    backup_dir.mkdir(parents=True, exist_ok=True)
    destination = backup_dir / f"{lua_path.name}.{timestamp_id()}.bak"
    shutil.copy2(lua_path, destination)
    return destination


def verify_lua_patch(config: AppConfig) -> LuaPatchStatus:
    status = check_lua(config)
    if not status.exists:
        return status
    if not status.patched:
        return LuaPatchStatus(status.lua_path, True, False, "Lua logger patch markers are not installed.")
    return LuaPatchStatus(status.lua_path, True, True, "Lua logger patch markers are installed.")


def patch_lua_logger(config: AppConfig) -> tuple[Path, Path]:
    lua_path = config.lua_path
    if not lua_path.exists():
        raise FileNotFoundError(f"Lua file not found: {lua_path}")
    text, newline = _read_text_preserving(lua_path)
    if BEGIN_MARKER not in text and "re.on_" not in text:
        raise RuntimeError("Expected REFramework callback insertion point was not found; refusing to patch.")

    backup_path = backup_lua(config)
    block = build_lua_block(config, newline)
    new_text = _replace_or_append_block(text, block, newline)
    lua_path.write_text(new_text, encoding="utf-8", newline="")
    return lua_path, backup_path


def restore_lua(config: AppConfig, backup: str | Path) -> Path:
    backup_path = Path(backup).expanduser()
    if not backup_path.is_absolute():
        backup_path = Path.cwd() / backup_path
    if not backup_path.exists():
        raise FileNotFoundError(f"Backup file not found: {backup_path}")
    lua_path = config.lua_path
    if lua_path.name != "RE9FreeCam.lua":
        raise RuntimeError(f"Configured Lua path does not look like RE9FreeCam.lua: {lua_path}")
    shutil.copy2(backup_path, lua_path)
    return lua_path


def build_lua_block(config: AppConfig, newline: str = "\n") -> str:
    control_name = _lua_string(config.control_file.name)
    status_name = _lua_string(config.status_file.name)
    pose_log_name = _lua_string(config.pose_log_file.name)
    interval = float(config.raw["lua_logger"]["default_interval_sec"])
    lines = [
        BEGIN_MARKER,
        "local re9_pose_logger = re9_pose_logger or {}",
        "-- REFramework Lua may reject absolute paths. json/io paths are relative to reframework/data here.",
        "re9_pose_logger.data_dir = re9_pose_logger.data_dir or \"\"",
        "re9_pose_logger.control_file = re9_pose_logger.control_file or \"" + control_name + "\"",
        "re9_pose_logger.status_file = re9_pose_logger.status_file or \"" + status_name + "\"",
        "re9_pose_logger.pose_log_file = re9_pose_logger.pose_log_file or \"" + pose_log_name + "\"",
        f"re9_pose_logger.interval_sec = re9_pose_logger.interval_sec or {interval:.6f}",
        "re9_pose_logger.enabled = re9_pose_logger.enabled ~= false",
        "re9_pose_logger.logging = re9_pose_logger.logging or false",
        "re9_pose_logger.session_id = re9_pose_logger.session_id or \"\"",
        "re9_pose_logger.rows_written = re9_pose_logger.rows_written or 0",
        "re9_pose_logger.last_error = re9_pose_logger.last_error or \"\"",
        "re9_pose_logger.last_sample_clock = re9_pose_logger.last_sample_clock or 0",
        "re9_pose_logger.last_control_clock = re9_pose_logger.last_control_clock or 0",
        "re9_pose_logger.session_start_clock = re9_pose_logger.session_start_clock or 0",
        "re9_pose_logger.file_handle = re9_pose_logger.file_handle or nil",
        "re9_pose_logger.last_command_id = re9_pose_logger.last_command_id or \"\"",
        "re9_pose_logger.scan_pose_enabled = re9_pose_logger.scan_pose_enabled or false",
        "re9_pose_logger.scan_segment_id = re9_pose_logger.scan_segment_id or \"\"",
        "re9_pose_logger.scan_x = re9_pose_logger.scan_x or 0",
        "re9_pose_logger.scan_y = re9_pose_logger.scan_y or 0",
        "re9_pose_logger.scan_z = re9_pose_logger.scan_z or 0",
        "re9_pose_logger.scan_x_start = re9_pose_logger.scan_x_start or 0",
        "re9_pose_logger.scan_y_start = re9_pose_logger.scan_y_start or 0",
        "re9_pose_logger.scan_z_start = re9_pose_logger.scan_z_start or 0",
        "re9_pose_logger.scan_x_end = re9_pose_logger.scan_x_end or 0",
        "re9_pose_logger.scan_y_end = re9_pose_logger.scan_y_end or 0",
        "re9_pose_logger.scan_z_end = re9_pose_logger.scan_z_end or 0",
        "re9_pose_logger.scan_yaw = re9_pose_logger.scan_yaw or 0",
        "re9_pose_logger.scan_yaw_start = re9_pose_logger.scan_yaw_start or 0",
        "re9_pose_logger.scan_yaw_end = re9_pose_logger.scan_yaw_end or 0",
        "re9_pose_logger.scan_pitch = re9_pose_logger.scan_pitch or 0",
        "re9_pose_logger.scan_pitch_start = re9_pose_logger.scan_pitch_start or 0",
        "re9_pose_logger.scan_pitch_end = re9_pose_logger.scan_pitch_end or 0",
        "re9_pose_logger.scan_fov = re9_pose_logger.scan_fov or nil",
        "re9_pose_logger.scan_fov_start = re9_pose_logger.scan_fov_start or nil",
        "re9_pose_logger.scan_fov_end = re9_pose_logger.scan_fov_end or nil",
        "re9_pose_logger.scan_start_clock = re9_pose_logger.scan_start_clock or 0",
        "re9_pose_logger.scan_duration_sec = re9_pose_logger.scan_duration_sec or 0",
        "re9_pose_logger.trajectory_enabled = re9_pose_logger.trajectory_enabled or false",
        "re9_pose_logger.trajectory_id = re9_pose_logger.trajectory_id or \"\"",
        "re9_pose_logger.trajectory_keyframes = re9_pose_logger.trajectory_keyframes or nil",
        "re9_pose_logger.trajectory_start_clock = re9_pose_logger.trajectory_start_clock or 0",
        "re9_pose_logger.trajectory_duration_sec = re9_pose_logger.trajectory_duration_sec or 0",
        "re9_pose_logger.trajectory_frame_count = re9_pose_logger.trajectory_frame_count or 0",
        "re9_pose_logger.physics_probe_status = re9_pose_logger.physics_probe_status or \"not run\"",
        "re9_pose_logger.physics_probe_contacts = re9_pose_logger.physics_probe_contacts or 0",
        "re9_pose_logger.physics_probe_rays = re9_pose_logger.physics_probe_rays or 0",
        "re9_pose_logger.physics_probe_pose_valid = re9_pose_logger.physics_probe_pose_valid ~= false",
        "re9_pose_logger.physics_probe_details = re9_pose_logger.physics_probe_details or \"\"",
        "re9_pose_logger.physics_probe_error = re9_pose_logger.physics_probe_error or \"\"",
        "re9_pose_logger.physics_clip_distance = re9_pose_logger.physics_clip_distance or 0.03",
        "re9_pose_logger.physics_near_distance = re9_pose_logger.physics_near_distance or 0.12",
        "re9_pose_logger.physics_sphere_radius = re9_pose_logger.physics_sphere_radius or 0.08",
        "re9_pose_logger.physics_saturation_invalid = re9_pose_logger.physics_saturation_invalid ~= false",
        "re9_pose_logger.physics_filter_layer = re9_pose_logger.physics_filter_layer or 0",
        "re9_pose_logger.physics_filter_mask_bit = re9_pose_logger.physics_filter_mask_bit or 31",
        "re9_pose_logger.new_scene_points_file = re9_pose_logger.new_scene_points_file or \"re9_new_scene_points.csv\"",
        "re9_pose_logger.new_scene_points_json_file = re9_pose_logger.new_scene_points_json_file or \"re9_new_scene_points.json\"",
        "re9_pose_logger.new_scene_point_count = re9_pose_logger.new_scene_point_count or 0",
        "re9_pose_logger.new_scene_last_point = re9_pose_logger.new_scene_last_point or \"\"",
        "local re9_pose_is_freecam_mode",
        "local re9_pose_get_pose",
        "",
        "local function re9_pose_escape_json(value)",
        "    value = tostring(value or \"\")",
        "    value = value:gsub('\\\\', '\\\\\\\\'):gsub('\"', '\\\\\"'):gsub('\\n', '\\\\n')",
        "    return value",
        "end",
        "",
        "local function re9_pose_basename(path)",
        "    path = tostring(path or \"\")",
        "    path = path:gsub('\\\\', '/')",
        "    local name = path:match('([^/]+)$') or path",
        "    if name == \"\" then name = \"re9_freecam_pose_log.csv\" end",
        "    return name",
        "end",
        "",
        "local function re9_pose_data_path(name)",
        "    name = re9_pose_basename(name)",
        "    if re9_pose_logger.data_dir == nil or re9_pose_logger.data_dir == \"\" then return name end",
        "    return re9_pose_logger.data_dir .. \"/\" .. name",
        "end",
        "",
        "local function re9_pose_csv_path(path)",
        "    return re9_pose_data_path(re9_pose_basename(path or re9_pose_logger.pose_log_file))",
        "end",
        "",
        "local function re9_pose_write_status()",
        "    local payload = {",
        "        session_id = re9_pose_logger.session_id or \"\",",
        "        logging = re9_pose_logger.logging == true,",
        "        rows_written = re9_pose_logger.rows_written or 0,",
        "        pose_log_file = re9_pose_logger.pose_log_file or \"\",",
        "        scan_pose_enabled = re9_pose_logger.scan_pose_enabled == true,",
        "        scan_segment_id = re9_pose_logger.scan_segment_id or \"\",",
        "        trajectory_enabled = re9_pose_logger.trajectory_enabled == true,",
        "        trajectory_id = re9_pose_logger.trajectory_id or \"\",",
        "        trajectory_frame_count = re9_pose_logger.trajectory_frame_count or 0,",
        "        physics_probe_status = re9_pose_logger.physics_probe_status or \"\",",
        "        physics_probe_contacts = re9_pose_logger.physics_probe_contacts or 0,",
        "        physics_probe_rays = re9_pose_logger.physics_probe_rays or 0,",
        "        physics_probe_pose_valid = re9_pose_logger.physics_probe_pose_valid == true,",
        "        physics_probe_details = re9_pose_logger.physics_probe_details or \"\",",
        "        physics_probe_error = re9_pose_logger.physics_probe_error or \"\",",
        "        new_scene_point_count = re9_pose_logger.new_scene_point_count or 0,",
        "        new_scene_last_point = re9_pose_logger.new_scene_last_point or \"\",",
        "        new_scene_points_file = re9_pose_logger.new_scene_points_file or \"\",",
        "        last_error = re9_pose_logger.last_error or \"\"",
        "    }",
        "    local ok, err = pcall(function()",
        "        if json ~= nil and json.dump_file ~= nil then",
        "            json.dump_file(re9_pose_logger.status_file, payload)",
        "        else",
        "            local f = assert(io.open(re9_pose_data_path(re9_pose_logger.status_file), \"w\"))",
        "            f:write(string.format('{\"session_id\":\"%s\",\"logging\":%s,\"rows_written\":%d,\"pose_log_file\":\"%s\",\"scan_pose_enabled\":%s,\"scan_segment_id\":\"%s\",\"trajectory_enabled\":%s,\"trajectory_id\":\"%s\",\"trajectory_frame_count\":%d,\"physics_probe_status\":\"%s\",\"physics_probe_contacts\":%d,\"physics_probe_rays\":%d,\"physics_probe_pose_valid\":%s,\"physics_probe_details\":\"%s\",\"physics_probe_error\":\"%s\",\"new_scene_point_count\":%d,\"new_scene_last_point\":\"%s\",\"new_scene_points_file\":\"%s\",\"last_error\":\"%s\"}',",
        "                re9_pose_escape_json(payload.session_id), tostring(payload.logging), tonumber(payload.rows_written) or 0,",
        "                re9_pose_escape_json(payload.pose_log_file), tostring(payload.scan_pose_enabled), re9_pose_escape_json(payload.scan_segment_id),",
        "                tostring(payload.trajectory_enabled), re9_pose_escape_json(payload.trajectory_id), tonumber(payload.trajectory_frame_count) or 0,",
        "                re9_pose_escape_json(payload.physics_probe_status), tonumber(payload.physics_probe_contacts) or 0, tonumber(payload.physics_probe_rays) or 0,",
        "                tostring(payload.physics_probe_pose_valid), re9_pose_escape_json(payload.physics_probe_details),",
        "                re9_pose_escape_json(payload.physics_probe_error), tonumber(payload.new_scene_point_count) or 0,",
        "                re9_pose_escape_json(payload.new_scene_last_point), re9_pose_escape_json(payload.new_scene_points_file),",
        "                re9_pose_escape_json(payload.last_error)))",
        "            f:close()",
        "        end",
        "    end)",
        "    if not ok then re9_pose_logger.last_error = tostring(err) end",
        "end",
        "",
        "local function re9_pose_read_control()",
        "    local ok, data = pcall(function()",
        "        if json ~= nil and json.load_file ~= nil then return json.load_file(re9_pose_logger.control_file) end",
        "        local f = io.open(re9_pose_data_path(re9_pose_logger.control_file), \"r\")",
        "        if f == nil then return nil end",
        "        local text = f:read(\"*a\")",
        "        f:close()",
        "        if text == nil then return nil end",
        "        return {",
        "            command = text:match('\"command\"%s*:%s*\"([^\"]+)\"'),",
        "            command_id = text:match('\"command_id\"%s*:%s*\"([^\"]+)\"'),",
        "            session_id = text:match('\"session_id\"%s*:%s*\"([^\"]+)\"'),",
        "            pose_log_file = text:match('\"pose_log_file\"%s*:%s*\"([^\"]+)\"'),",
        "            interval_sec = tonumber(text:match('\"interval_sec\"%s*:%s*([%-%d%.]+)')),",
        "            x = tonumber(text:match('\"x\"%s*:%s*([%-%d%.]+)')),",
        "            y = tonumber(text:match('\"y\"%s*:%s*([%-%d%.]+)')),",
        "            z = tonumber(text:match('\"z\"%s*:%s*([%-%d%.]+)')),",
        "            x_end = tonumber(text:match('\"x_end\"%s*:%s*([%-%d%.]+)')),",
        "            y_end = tonumber(text:match('\"y_end\"%s*:%s*([%-%d%.]+)')),",
        "            z_end = tonumber(text:match('\"z_end\"%s*:%s*([%-%d%.]+)')),",
        "            yaw = tonumber(text:match('\"yaw\"%s*:%s*([%-%d%.]+)')),",
        "            yaw_end = tonumber(text:match('\"yaw_end\"%s*:%s*([%-%d%.]+)')),",
        "            duration_sec = tonumber(text:match('\"duration_sec\"%s*:%s*([%-%d%.]+)')),",
        "            pitch = tonumber(text:match('\"pitch\"%s*:%s*([%-%d%.]+)')),",
        "            pitch_end = tonumber(text:match('\"pitch_end\"%s*:%s*([%-%d%.]+)')),",
        "            fov = tonumber(text:match('\"fov\"%s*:%s*([%-%d%.]+)')),",
        "            fov_end = tonumber(text:match('\"fov_end\"%s*:%s*([%-%d%.]+)')),",
        "            segment_id = text:match('\"segment_id\"%s*:%s*\"([^\"]+)\"')",
        "        }",
        "    end)",
        "    if ok then return data end",
        "    re9_pose_logger.last_error = tostring(data)",
        "    return nil",
        "end",
        "",
        "local function re9_pose_vec3(x, y, z)",
        "    if Vector3f ~= nil and Vector3f.new ~= nil then return Vector3f.new(x, y, z) end",
        "    return { x = x, y = y, z = z }",
        "end",
        "",
        "local function re9_pose_call_query(query, method_name, ...)",
        "    if query == nil or query.call == nil then return false, \"query has no call method\" end",
        "    local ok, result = pcall(function(...) return query:call(method_name, ...) end, ...)",
        "    if ok then return true, result end",
        "    return false, tostring(result)",
        "end",
        "",
        "local function re9_pose_contact_min_distance(result, count)",
        "    local min_distance = nil",
        "    local max_index = (tonumber(count) or 0) - 1",
        "    if max_index > 7 then max_index = 7 end",
        "    for i = 0, max_index do",
        "        local ok_cp, cp = pcall(function() return result:call(\"getContactPoint\", i) end)",
        "        if ok_cp and cp ~= nil then",
        "            local d = nil",
        "            if type(cp) == \"table\" then d = tonumber(cp.Distance or cp.distance) end",
        "            if d == nil then pcall(function() d = tonumber(cp:get_field(\"Distance\")) end) end",
        "            if d == nil then pcall(function() d = tonumber(cp:call(\"get_Distance\")) end) end",
        "            if d ~= nil and (min_distance == nil or d < min_distance) then min_distance = d end",
        "        end",
        "    end",
        "    return min_distance",
        "end",
        "",
        "local function re9_pose_run_single_cast_ray(origin, target, inside_hits, filter)",
        "    if sdk == nil then return false, \"sdk unavailable\", 0 end",
        "    local physics_type = sdk.find_type_definition(\"via.physics.System\")",
        "    if physics_type == nil then return false, \"via.physics.System type not found\", 0 end",
        "    local query = sdk.create_instance(\"via.physics.CastRayQuery\")",
        "    if query == nil then query = sdk.create_instance(\"via.physics.CastRayQuery\", true) end",
        "    if query == nil then return false, \"could not create CastRayQuery\", 0 end",
        "    re9_pose_call_query(query, \"clearOptions\")",
        "    re9_pose_call_query(query, \"enableAllHits\")",
        "    re9_pose_call_query(query, \"enableOneHitBreak\")",
        "    if inside_hits then re9_pose_call_query(query, \"enableInsideHits\") end",
        "    if filter ~= nil then",
        "        re9_pose_call_query(query, \"copyFilterInfo(via.physics.FilterInfo)\", filter)",
        "        re9_pose_call_query(query, \"copyFilterInfo\", filter)",
        "        re9_pose_call_query(query, \"set_FilterInfo(via.physics.FilterInfo)\", filter)",
        "        re9_pose_call_query(query, \"set_FilterInfo\", filter)",
        "    end",
        "    local ok_set, set_err = re9_pose_call_query(query, \"setRay(via.vec3, via.vec3)\", origin, target)",
        "    if not ok_set then ok_set, set_err = re9_pose_call_query(query, \"setRay\", origin, target) end",
        "    if not ok_set then return false, \"setRay failed: \" .. tostring(set_err), 0 end",
        "    local ok_cast, result = pcall(function() return sdk.call_native_func(nil, physics_type, \"castRay(via.physics.CastRayQuery)\", query) end)",
        "    if not ok_cast then ok_cast, result = pcall(function() return sdk.call_native_func(nil, physics_type, \"castRay\", query) end) end",
        "    if not ok_cast or result == nil then return false, \"castRay failed: \" .. tostring(result), 0 end",
        "    local ok_num, num = pcall(function() return result:call(\"get_NumContactPoints\") end)",
        "    if not ok_num then ok_num, num = pcall(function() return result:call(\"get_NumContactPoints()\") end) end",
        "    if not ok_num then return false, \"get_NumContactPoints failed: \" .. tostring(num), 0 end",
        "    num = tonumber(num) or 0",
        "    return true, \"api_ok\", num, re9_pose_contact_min_distance(result, num)",
        "end",
        "",
        "local function re9_pose_create_filter_info(layer, mask_bits)",
        "    if sdk == nil then return nil end",
        "    local filter = sdk.create_instance(\"via.physics.FilterInfo\")",
        "    if filter == nil then filter = sdk.create_instance(\"via.physics.FilterInfo\", true) end",
        "    if filter ~= nil then",
        "        pcall(function() filter:call(\".ctor\") end)",
        "        local filter_layer = tonumber(layer) or 0",
        "        local filter_mask = tonumber(mask_bits) or 0xffffffff",
        "        pcall(function() filter:call(\"set_Layer\", filter_layer) end)",
        "        pcall(function() filter:call(\"set_Layer(System.UInt32)\", filter_layer) end)",
        "        pcall(function() filter:call(\"set_MaskBits\", filter_mask) end)",
        "        pcall(function() filter:call(\"set_MaskBits(System.UInt32)\", filter_mask) end)",
        "    end",
        "    return filter",
        "end",
        "",
        "local function re9_pose_current_filter()",
        "    local layer = math.floor(tonumber(re9_pose_logger.physics_filter_layer) or 0)",
        "    if layer < 0 then layer = 0 elseif layer > 31 then layer = 31 end",
        "    local mask_bit = math.floor(tonumber(re9_pose_logger.physics_filter_mask_bit) or 31)",
        "    if mask_bit < 0 then mask_bit = 0 elseif mask_bit > 31 then mask_bit = 31 end",
        "    local mask_bits = 2 ^ mask_bit",
        "    return re9_pose_create_filter_info(layer, mask_bits), layer, mask_bit, mask_bits",
        "end",
        "",
        "local function re9_pose_run_closest_sphere(center, radius, filter, mask_bits)",
        "    if sdk == nil then return false, \"sdk unavailable\", 0 end",
        "    local physics_type = sdk.find_type_definition(\"via.physics.System\")",
        "    if physics_type == nil then return false, \"via.physics.System type not found\", 0 end",
        "    local sphere = sdk.create_instance(\"via.Sphere\")",
        "    if sphere == nil then sphere = sdk.create_instance(\"via.Sphere\", true) end",
        "    if sphere == nil then return false, \"could not create via.Sphere\", 0 end",
        "    pcall(function() sphere:call(\".ctor\", center, radius) end)",
        "    pcall(function() sphere:call(\"setPos\", center) end)",
        "    pcall(function() sphere:call(\"setRadius\", radius) end)",
        "    pcall(function() sphere:call(\"set_Center\", center) end)",
        "    pcall(function() sphere:call(\"set_Radius\", radius) end)",
        "    pcall(function() sphere:set_field(\"pos\", center) end)",
        "    pcall(function() sphere:set_field(\"r\", radius) end)",
        "    if filter == nil then filter = re9_pose_create_filter_info() end",
        "    if filter == nil then return false, \"could not create FilterInfo\", 0 end",
        "    local mask = tonumber(mask_bits) or 0xffffffff",
        "    local ok_cast, result = pcall(function() return sdk.call_native_func(nil, physics_type, \"closestSphere(via.Sphere, System.UInt32, via.physics.FilterInfo)\", sphere, mask, filter) end)",
        "    if not ok_cast then ok_cast, result = pcall(function() return sdk.call_native_func(nil, physics_type, \"closestSphere\", sphere, mask, filter) end) end",
        "    if not ok_cast or result == nil then return false, \"closestSphere failed: \" .. tostring(result), 0 end",
        "    local ok_num, num = pcall(function() return result:call(\"get_NumContactPoints\") end)",
        "    if not ok_num then ok_num, num = pcall(function() return result:call(\"get_NumContactPoints()\") end) end",
        "    if not ok_num then return false, \"closestSphere get_NumContactPoints failed: \" .. tostring(num), 0 end",
        "    return true, \"api_ok\", tonumber(num) or 0",
        "end",
        "",
        "local function re9_pose_run_resolve_penetration(center, radius, filter)",
        "    if sdk == nil then return false, \"sdk unavailable\", false end",
        "    local physics_type = sdk.find_type_definition(\"via.physics.System\")",
        "    if physics_type == nil then return false, \"via.physics.System type not found\", false end",
        "    local sphere = sdk.create_instance(\"via.Sphere\")",
        "    if sphere == nil then sphere = sdk.create_instance(\"via.Sphere\", true) end",
        "    if sphere == nil then return false, \"could not create via.Sphere\", false end",
        "    pcall(function() sphere:call(\".ctor\", center, radius) end)",
        "    pcall(function() sphere:call(\"setPos\", center) end)",
        "    pcall(function() sphere:call(\"setRadius\", radius) end)",
        "    pcall(function() sphere:call(\"set_Center\", center) end)",
        "    pcall(function() sphere:call(\"set_Radius\", radius) end)",
        "    pcall(function() sphere:set_field(\"pos\", center) end)",
        "    pcall(function() sphere:set_field(\"r\", radius) end)",
        "    if filter == nil then filter = re9_pose_create_filter_info() end",
        "    if filter == nil then return false, \"could not create FilterInfo\", false end",
        "    local ok_hit, result = pcall(function() return sdk.call_native_func(nil, physics_type, \"resolvePenetration(via.Sphere, via.physics.FilterInfo)\", sphere, filter) end)",
        "    if not ok_hit then ok_hit, result = pcall(function() return sdk.call_native_func(nil, physics_type, \"resolvePenetration\", sphere, filter) end) end",
        "    if not ok_hit then return false, \"resolvePenetration failed: \" .. tostring(result), false end",
        "    return true, \"api_ok\", result == true",
        "end",
        "",
        "local function re9_pose_probe_dirs()",
        "    local dirs = {}",
        "    for dx = -1, 1 do",
        "        for dy = -1, 1 do",
        "            for dz = -1, 1 do",
        "                if not (dx == 0 and dy == 0 and dz == 0) then",
        "                    local len = math.sqrt(dx * dx + dy * dy + dz * dz)",
        "                    table.insert(dirs, { string.format(\"%+d%+d%+d\", dx, dy, dz), dx / len, dy / len, dz / len })",
        "                end",
        "            end",
        "        end",
        "    end",
        "    return dirs",
        "end",
        "",
        "local function re9_pose_forward_dir(yaw_value, pitch_value)",
        "    local yaw = tonumber(yaw_value) or 0",
        "    local pitch = tonumber(pitch_value) or 0",
        "    local cp = math.cos(pitch)",
        "    return math.sin(yaw) * cp, -math.sin(pitch), math.cos(yaw) * cp",
        "end",
        "",
        "local function re9_pose_call_obj(obj, method_name, ...)",
        "    if obj == nil or obj.call == nil then return false, \"object has no call method\" end",
        "    local ok, result = pcall(function(...) return obj:call(method_name, ...) end, ...)",
        "    if ok then return true, result end",
        "    return false, tostring(result)",
        "end",
        "",
        "local function re9_pose_obj_field(obj, field_name)",
        "    if obj == nil then return nil end",
        "    local ok, value = pcall(function() return obj:get_field(field_name) end)",
        "    if ok then return value end",
        "    return nil",
        "end",
        "",
        "local function re9_pose_get_singleton(type_name)",
        "    if sdk == nil or sdk.get_managed_singleton == nil then return nil, \"sdk.get_managed_singleton unavailable\" end",
        "    local ok, obj = pcall(function() return sdk.get_managed_singleton(type_name) end)",
        "    if ok and obj ~= nil then return obj, \"singleton\" end",
        "    return nil, tostring(obj)",
        "end",
        "",
        "local function re9_pose_array_elements(value)",
        "    if value == nil then return {} end",
        "    local ok, elements = pcall(function() return value:get_elements() end)",
        "    if ok and elements ~= nil then return elements end",
        "    return {}",
        "end",
        "",
        "local function re9_pose_scene_by_method(method_name)",
        "    if sdk == nil then return nil, \"sdk unavailable\" end",
        "    local scene_manager_type = sdk.find_type_definition(\"via.SceneManager\")",
        "    if scene_manager_type == nil then return nil, \"via.SceneManager type missing\" end",
        "    local method = scene_manager_type:get_method(method_name)",
        "    if method == nil then return nil, method_name .. \" method missing\" end",
        "    local ok, scene = pcall(function() return method:call(nil) end)",
        "    if ok and scene ~= nil then return scene, method_name end",
        "    return nil, tostring(scene)",
        "end",
        "",
        "local function re9_pose_find_scene_components(type_name, parts)",
        "    local component_type = nil",
        "    local ok_type, type_result = pcall(function() return sdk.typeof(type_name) end)",
        "    if ok_type then component_type = type_result end",
        "    if component_type == nil then",
        "        table.insert(parts, type_name .. \" typeof=nil\")",
        "        return {}",
        "    end",
        "    local out = {}",
        "    local seen = {}",
        "    local scene_methods = {\"get_CurrentScene\", \"get_MainScene\", \"get_ResidentScene\"}",
        "    for _, method_name in ipairs(scene_methods) do",
        "        local scene, scene_src = re9_pose_scene_by_method(method_name)",
        "        if scene ~= nil then",
        "            local ok_find, components = pcall(function() return scene:call(\"findComponents(System.Type)\", component_type) end)",
        "            if not ok_find then ok_find, components = pcall(function() return scene:call(\"findComponents\", component_type) end) end",
        "            local elements = re9_pose_array_elements(components)",
        "            local count = 0",
        "            for _, component in ipairs(elements) do",
        "                if component ~= nil and seen[component] ~= true then",
        "                    seen[component] = true",
        "                    table.insert(out, component)",
        "                    count = count + 1",
        "                end",
        "            end",
        "            table.insert(parts, type_name .. \"@\" .. tostring(scene_src) .. \"=\" .. tostring(count))",
        "        else",
        "            table.insert(parts, type_name .. \"@\" .. tostring(method_name) .. \"=scene_nil:\" .. tostring(scene_src))",
        "        end",
        "    end",
        "    return out",
        "end",
        "",
        "local function re9_pose_vec3_text(value)",
        "    if value == nil then return \"nil\" end",
        "    local x = nil",
        "    local y = nil",
        "    local z = nil",
        "    pcall(function() x = value.x or value[1] end)",
        "    pcall(function() y = value.y or value[2] end)",
        "    pcall(function() z = value.z or value[3] end)",
        "    return string.format(\"(%.2f,%.2f,%.2f)\", tonumber(x) or 0, tonumber(y) or 0, tonumber(z) or 0)",
        "end",
        "",
        "local function re9_pose_probe_camera_interp(label, obj, parts)",
        "    if obj == nil then return 0 end",
        "    local score = 0",
        "    local ok_rate, rate = re9_pose_call_obj(obj, \"get_CollisionStateRate\")",
        "    if not ok_rate then ok_rate, rate = re9_pose_call_obj(obj, \"get_CollisionStateRate()\") end",
        "    local ok_pos, pos = re9_pose_call_obj(obj, \"get_CameraPosition\")",
        "    if not ok_pos then ok_pos, pos = re9_pose_call_obj(obj, \"get_CameraPosition()\") end",
        "    if ok_rate and tonumber(rate) ~= nil and math.abs(tonumber(rate)) > 0.001 then score = score + 1 end",
        "    table.insert(parts, label .. \":rate=\" .. tostring(ok_rate and rate or \"?\") .. \":pos=\" .. tostring(ok_pos and re9_pose_vec3_text(pos) or \"?\"))",
        "    local collision = re9_pose_obj_field(obj, \"_CollisionInterpolation\")",
        "    if collision ~= nil then",
        "        local ok_radius, radius = re9_pose_call_obj(collision, \"getCollisionRadius\")",
        "        local ok_range, range = re9_pose_call_obj(collision, \"getCollisionRange\")",
        "        local ok_avoid, avoid = re9_pose_call_obj(collision, \"get_AvoidRate\")",
        "        local ok_cpos, cpos = re9_pose_call_obj(collision, \"get_CameraPosition\")",
        "        if ok_avoid and tonumber(avoid) ~= nil and math.abs(tonumber(avoid)) > 0.001 then score = score + 1 end",
        "        table.insert(parts, label .. \":collision=live:r=\" .. tostring(ok_radius and radius or \"?\") .. \":range=\" .. tostring(ok_range and range or \"?\") .. \":avoid=\" .. tostring(ok_avoid and avoid or \"?\") .. \":cpos=\" .. tostring(ok_cpos and re9_pose_vec3_text(cpos) or \"?\"))",
        "    else",
        "        table.insert(parts, label .. \":collision=nil\")",
        "    end",
        "    return score",
        "end",
        "",
        "local function re9_pose_probe_camera_collision_system()",
        "    local parts = {}",
        "    local score = 0",
        "    local found = 0",
        "    local fps, fps_src = re9_pose_get_singleton(\"app.PlayerFPSCameraController\")",
        "    local tps, tps_src = re9_pose_get_singleton(\"app.PlayerTPSCameraController\")",
        "    if fps ~= nil then",
        "        found = found + 1",
        "        table.insert(parts, \"FPSController=\" .. tostring(fps_src))",
        "        local ok_interp, interp = re9_pose_call_obj(fps, \"get_FPSActionInterpolation\")",
        "        if ok_interp and interp ~= nil then score = score + re9_pose_probe_camera_interp(\"FPSInterp\", interp, parts) else table.insert(parts, \"FPSInterp=nil\") end",
        "        local ok_pos, pos = re9_pose_call_obj(fps, \"get_CameraPositionWithMovementShake\")",
        "        table.insert(parts, \"FPSControllerPos=\" .. tostring(ok_pos and re9_pose_vec3_text(pos) or \"?\"))",
        "    else",
        "        table.insert(parts, \"FPSController=nil:\" .. tostring(fps_src))",
        "    end",
        "    if tps ~= nil then",
        "        found = found + 1",
        "        table.insert(parts, \"TPSController=\" .. tostring(tps_src))",
        "        local ok_interp, interp = re9_pose_call_obj(tps, \"get_TPSActionInterpolation\")",
        "        if ok_interp and interp ~= nil then score = score + re9_pose_probe_camera_interp(\"TPSInterp\", interp, parts) else table.insert(parts, \"TPSInterp=nil\") end",
        "    else",
        "        table.insert(parts, \"TPSController=nil:\" .. tostring(tps_src))",
        "    end",
        "    local fps_interp, fps_interp_src = re9_pose_get_singleton(\"app.PlayerCameraFPSActionInterpolation\")",
        "    if fps_interp ~= nil then found = found + 1; score = score + re9_pose_probe_camera_interp(\"FPSInterpSingleton\", fps_interp, parts) else table.insert(parts, \"FPSInterpSingleton=nil:\" .. tostring(fps_interp_src)) end",
        "    local tps_interp, tps_interp_src = re9_pose_get_singleton(\"app.PlayerCameraTPSActionInterpolation\")",
        "    if tps_interp ~= nil then found = found + 1; score = score + re9_pose_probe_camera_interp(\"TPSInterpSingleton\", tps_interp, parts) else table.insert(parts, \"TPSInterpSingleton=nil:\" .. tostring(tps_interp_src)) end",
        "    local scene_fps = re9_pose_find_scene_components(\"app.PlayerFPSCameraController\", parts)",
        "    for index, component in ipairs(scene_fps) do",
        "        found = found + 1",
        "        local ok_interp, interp = re9_pose_call_obj(component, \"get_FPSActionInterpolation\")",
        "        if ok_interp and interp ~= nil then score = score + re9_pose_probe_camera_interp(\"SceneFPS\" .. tostring(index), interp, parts) else table.insert(parts, \"SceneFPS\" .. tostring(index) .. \":interp=nil\") end",
        "        local ok_pos, pos = re9_pose_call_obj(component, \"get_CameraPositionWithMovementShake\")",
        "        table.insert(parts, \"SceneFPS\" .. tostring(index) .. \":pos=\" .. tostring(ok_pos and re9_pose_vec3_text(pos) or \"?\"))",
        "    end",
        "    local scene_tps = re9_pose_find_scene_components(\"app.PlayerTPSCameraController\", parts)",
        "    for index, component in ipairs(scene_tps) do",
        "        found = found + 1",
        "        local ok_interp, interp = re9_pose_call_obj(component, \"get_TPSActionInterpolation\")",
        "        if ok_interp and interp ~= nil then score = score + re9_pose_probe_camera_interp(\"SceneTPS\" .. tostring(index), interp, parts) else table.insert(parts, \"SceneTPS\" .. tostring(index) .. \":interp=nil\") end",
        "    end",
        "    local scene_fps_interp = re9_pose_find_scene_components(\"app.PlayerCameraFPSActionInterpolation\", parts)",
        "    for index, component in ipairs(scene_fps_interp) do",
        "        found = found + 1",
        "        score = score + re9_pose_probe_camera_interp(\"SceneFPSInterp\" .. tostring(index), component, parts)",
        "    end",
        "    local scene_tps_interp = re9_pose_find_scene_components(\"app.PlayerCameraTPSActionInterpolation\", parts)",
        "    for index, component in ipairs(scene_tps_interp) do",
        "        found = found + 1",
        "        score = score + re9_pose_probe_camera_interp(\"SceneTPSInterp\" .. tostring(index), component, parts)",
        "    end",
        "    re9_pose_logger.physics_probe_status = score > 0 and \"camera_collision_active\" or \"camera_collision_probe\"",
        "    re9_pose_logger.physics_probe_pose_valid = not (score > 0)",
        "    re9_pose_logger.physics_probe_contacts = score",
        "    re9_pose_logger.physics_probe_rays = found",
        "    re9_pose_logger.physics_probe_details = table.concat(parts, \"; \")",
        "    re9_pose_logger.physics_probe_error = score > 0 and \"Camera collision system reports active collision/avoidance.\" or \"No live camera collision response found; scene component scan may not expose FreeCam collision objects.\"",
        "    re9_pose_write_status()",
        "end",
        "",
        "local function re9_pose_run_physics_probe()",
        "    if not re9_pose_is_freecam_mode() or freecam_pos == nil then",
        "        re9_pose_logger.physics_probe_status = \"freecam disabled\"",
        "        re9_pose_logger.physics_probe_error = \"Enable FreeCam before physics probe\"",
        "        re9_pose_write_status()",
        "        return",
        "    end",
        "    local x, y, z, yaw_value, pitch_value = re9_pose_get_pose()",
        "    local origin = re9_pose_vec3(x, y, z)",
        "    local ray_len = 0.35",
        "    local clip_distance = tonumber(re9_pose_logger.physics_clip_distance) or 0.03",
        "    local near_distance = tonumber(re9_pose_logger.physics_near_distance) or 0.12",
        "    local sphere_radius = tonumber(re9_pose_logger.physics_sphere_radius) or 0.08",
        "    local filter, filter_layer, filter_mask_bit, filter_mask_bits = re9_pose_current_filter()",
        "    local ok_sphere, sphere_msg, sphere_contacts = re9_pose_run_closest_sphere(origin, sphere_radius, filter, filter_mask_bits)",
        "    local ok_penetration, penetration_msg, sphere_penetrating = re9_pose_run_resolve_penetration(origin, sphere_radius, filter)",
        "    local sphere_sweep = {0.01, 0.03, 0.06, sphere_radius}",
        "    local sphere_sweep_parts = {}",
        "    local sphere_sweep_ok = 0",
        "    local sphere_sweep_hits = 0",
        "    for _, radius in ipairs(sphere_sweep) do",
        "        local ok_p, msg_p, hit_p = re9_pose_run_resolve_penetration(origin, radius, filter)",
        "        if ok_p then",
        "            sphere_sweep_ok = sphere_sweep_ok + 1",
        "            if hit_p == true then sphere_sweep_hits = sphere_sweep_hits + 1 end",
        "            table.insert(sphere_sweep_parts, string.format(\"%.3f:%s\", radius, tostring(hit_p)))",
        "        else",
        "            table.insert(sphere_sweep_parts, string.format(\"%.3f:err\", radius))",
        "        end",
        "    end",
        "    local inside_contacts = 0",
        "    local min_probe_distance = nil",
        "    local near_zero_dirs = 0",
        "    local close_dirs = 0",
        "    local rays = 0",
        "    local errors = {}",
        "    local hit_dirs = 0",
        "    local detail_parts = {}",
        "    local dirs = re9_pose_probe_dirs()",
        "    for _, item in ipairs(dirs) do",
        "        local label = item[1]",
        "        local target = re9_pose_vec3(x + item[2] * ray_len, y + item[3] * ray_len, z + item[4] * ray_len)",
        "        local ok_i, msg_i, count_i, dist_i = re9_pose_run_single_cast_ray(origin, target, true, filter)",
        "        rays = rays + 1",
        "        if ok_i then",
        "            local c = tonumber(count_i) or 0",
        "            inside_contacts = inside_contacts + c",
        "            if c > 0 then hit_dirs = hit_dirs + 1 end",
        "        else",
        "            table.insert(errors, label .. \":inside:\" .. tostring(msg_i))",
        "        end",
        "        if dist_i ~= nil and (min_probe_distance == nil or dist_i < min_probe_distance) then min_probe_distance = dist_i end",
        "        if dist_i ~= nil and dist_i <= clip_distance then near_zero_dirs = near_zero_dirs + 1 end",
        "        if dist_i ~= nil and dist_i < near_distance then close_dirs = close_dirs + 1 end",
        "    end",
        "    local fx, fy, fz = re9_pose_forward_dir(yaw_value, pitch_value)",
        "    local ok_f, msg_f, count_f, dist_f = re9_pose_run_single_cast_ray(origin, re9_pose_vec3(x + fx * ray_len, y + fy * ray_len, z + fz * ray_len), true, filter)",
        "    rays = rays + 1",
        "    if ok_f then",
        "        local c = tonumber(count_f) or 0",
        "        inside_contacts = inside_contacts + c",
        "        if c > 0 then hit_dirs = hit_dirs + 1 end",
        "        if dist_f ~= nil and (min_probe_distance == nil or dist_f < min_probe_distance) then min_probe_distance = dist_f end",
        "        if dist_f ~= nil and dist_f <= clip_distance then near_zero_dirs = near_zero_dirs + 1 end",
        "        if dist_f ~= nil and dist_f < near_distance then close_dirs = close_dirs + 1 end",
        "    else",
        "        table.insert(errors, \"forward:inside:\" .. tostring(msg_f))",
        "    end",
        "    table.insert(detail_parts, \"filter_layer=\" .. tostring(filter_layer) .. \" mask_bit=\" .. tostring(filter_mask_bit) .. \" mask=\" .. tostring(filter_mask_bits))",
        "    table.insert(detail_parts, \"sphere_r=\" .. string.format(\"%.3f\", sphere_radius) .. \" sphere_penetrating=\" .. tostring(sphere_penetrating) .. \" penetration_ok=\" .. tostring(ok_penetration) .. \" sphere_contacts=\" .. tostring(sphere_contacts or \"?\") .. \" closest_ok=\" .. tostring(ok_sphere))",
        "    table.insert(detail_parts, \"sphere_sweep=\" .. table.concat(sphere_sweep_parts, \",\"))",
        "    table.insert(detail_parts, \"ray_hit_dirs=\" .. tostring(hit_dirs) .. \"/\" .. tostring(rays) .. \" ray_contacts=\" .. tostring(inside_contacts) .. \" close_dirs=\" .. tostring(close_dirs) .. \" clip_dirs=\" .. tostring(near_zero_dirs))",
        "    table.insert(detail_parts, \"min_d=\" .. tostring(min_probe_distance ~= nil and string.format(\"%.4f\", min_probe_distance) or \"?\") .. \" forward_i=\" .. tostring(count_f or \"?\") .. \" forward_d=\" .. tostring(dist_f ~= nil and string.format(\"%.4f\", dist_f) or \"?\"))",
        "    if not ok_sphere then table.insert(errors, \"closestSphere:\" .. tostring(sphere_msg)) end",
        "    if not ok_penetration then table.insert(errors, \"resolvePenetration:\" .. tostring(penetration_msg)) end",
        "    re9_pose_logger.physics_probe_contacts = hit_dirs",
        "    re9_pose_logger.physics_probe_rays = rays",
        "    re9_pose_logger.physics_probe_details = table.concat(detail_parts, \"; \")",
        "    local ray_saturated = rays > 0 and hit_dirs >= rays and near_zero_dirs == 0",
        "    local sphere_saturated = sphere_sweep_ok > 0 and sphere_sweep_hits >= sphere_sweep_ok and ray_saturated",
        "    local saturation_suspect = sphere_saturated and re9_pose_logger.physics_saturation_invalid == true",
        "    local ray_suspect = near_zero_dirs >= 2 or (min_probe_distance ~= nil and min_probe_distance <= clip_distance)",
        "    local sphere_suspect = ok_penetration and sphere_penetrating == true and not sphere_saturated",
        "    local suspect = saturation_suspect or sphere_suspect or ray_suspect",
        "    re9_pose_logger.physics_probe_pose_valid = not suspect",
        "    if #errors > 0 and (not ok_sphere or not ok_penetration) then",
        "        re9_pose_logger.physics_probe_status = \"error\"",
        "        re9_pose_logger.physics_probe_error = table.concat(errors, \" | \")",
        "    elseif sphere_saturated then",
        "        re9_pose_logger.physics_probe_status = saturation_suspect and \"probe_saturated_invalid\" or \"probe_saturated\"",
        "        re9_pose_logger.physics_probe_error = \"physics signals are saturated; sphere_sweep=\" .. table.concat(sphere_sweep_parts, \",\") .. \" hit_dirs=\" .. tostring(hit_dirs) .. \"/\" .. tostring(rays) .. \" min_distance=\" .. tostring(min_probe_distance or \"?\")",
        "    elseif suspect then",
        "        re9_pose_logger.physics_probe_status = sphere_suspect and \"sphere_penetration\" or \"suspect_clip\"",
        "        re9_pose_logger.physics_probe_error = \"sphere_penetrating=\" .. tostring(sphere_penetrating) .. \" sphere_contacts=\" .. tostring(sphere_contacts or \"?\") .. \" near_zero_dirs=\" .. tostring(near_zero_dirs) .. \" min_distance=\" .. tostring(min_probe_distance or \"?\") .. \" clip_distance=\" .. tostring(clip_distance)",
        "    elseif min_probe_distance ~= nil and min_probe_distance < near_distance then",
        "        re9_pose_logger.physics_probe_status = \"near_surface\"",
        "        re9_pose_logger.physics_probe_error = \"min_distance=\" .. tostring(min_probe_distance) .. \" near_distance=\" .. tostring(near_distance) .. \" sphere_contacts=\" .. tostring(sphere_contacts or \"?\")",
        "    else",
        "        re9_pose_logger.physics_probe_status = \"api_ok_clear\"",
        "        re9_pose_logger.physics_probe_error = \"\"",
        "    end",
        "    re9_pose_write_status()",
        "end",
        "",
        "local function re9_pose_scan_physics_filter_bits()",
        "    if not re9_pose_is_freecam_mode() or freecam_pos == nil then",
        "        re9_pose_logger.physics_probe_status = \"freecam disabled\"",
        "        re9_pose_logger.physics_probe_error = \"Enable FreeCam before scanning physics filters\"",
        "        re9_pose_write_status()",
        "        return",
        "    end",
        "    local x, y, z, yaw_value, pitch_value = re9_pose_get_pose()",
        "    local origin = re9_pose_vec3(x, y, z)",
        "    local sphere_radius = tonumber(re9_pose_logger.physics_sphere_radius) or 0.08",
        "    local layer = math.floor(tonumber(re9_pose_logger.physics_filter_layer) or 0)",
        "    if layer < 0 then layer = 0 elseif layer > 31 then layer = 31 end",
        "    local fx, fy, fz = re9_pose_forward_dir(yaw_value, pitch_value)",
        "    local forward_target = re9_pose_vec3(x + fx * 0.35, y + fy * 0.35, z + fz * 0.35)",
        "    local parts = {}",
        "    local active = 0",
        "    for bit = 0, 31 do",
        "        local mask = 2 ^ bit",
        "        local filter = re9_pose_create_filter_info(layer, mask)",
        "        local ok_p, msg_p, penetrating = re9_pose_run_resolve_penetration(origin, sphere_radius, filter)",
        "        local ok_c, msg_c, closest_contacts = re9_pose_run_closest_sphere(origin, sphere_radius, filter, mask)",
        "        local ok_r, msg_r, ray_contacts, ray_dist = re9_pose_run_single_cast_ray(origin, forward_target, true, filter)",
        "        local c = tonumber(closest_contacts) or 0",
        "        local r = tonumber(ray_contacts) or 0",
        "        if penetrating == true or c > 0 or r > 0 then",
        "            active = active + 1",
        "            table.insert(parts, \"b\" .. tostring(bit) .. \":p\" .. tostring(penetrating == true) .. \":c\" .. tostring(c) .. \":r\" .. tostring(r) .. \":d\" .. tostring(ray_dist ~= nil and string.format(\"%.3f\", ray_dist) or \"?\"))",
        "        elseif not ok_p or not ok_c or not ok_r then",
        "            table.insert(parts, \"b\" .. tostring(bit) .. \":err\")",
        "        end",
        "    end",
        "    re9_pose_logger.physics_probe_status = \"filter_scan\"",
        "    re9_pose_logger.physics_probe_pose_valid = true",
        "    re9_pose_logger.physics_probe_contacts = active",
        "    re9_pose_logger.physics_probe_rays = 32",
        "    re9_pose_logger.physics_probe_details = \"filter_layer=\" .. tostring(layer) .. \" active_bits=\" .. tostring(active) .. \"; \" .. table.concat(parts, \"; \")",
        "    re9_pose_logger.physics_probe_error = \"Compare this at a normal point and a clipped point; choose a mask bit that changes.\"",
        "    re9_pose_write_status()",
        "end",
        "",
        "local function re9_pose_start(session_id, pose_log_file, interval_sec)",
        "    if io == nil or io.open == nil then",
        "        re9_pose_logger.last_error = \"io.open unavailable in this REFramework Lua environment\"",
        "        re9_pose_write_status()",
        "        return",
        "    end",
        "    if re9_pose_logger.file_handle ~= nil then pcall(function() re9_pose_logger.file_handle:close() end) end",
        "    re9_pose_logger.session_id = session_id or os.date(\"%Y%m%d_%H%M%S\")",
        "    re9_pose_logger.pose_log_file = re9_pose_csv_path(pose_log_file or re9_pose_logger.pose_log_file)",
        "    re9_pose_logger.interval_sec = tonumber(interval_sec) or re9_pose_logger.interval_sec",
        "    re9_pose_logger.rows_written = 0",
        "    re9_pose_logger.session_start_clock = os.clock()",
        "    re9_pose_logger.last_sample_clock = 0",
        "    re9_pose_logger.last_error = \"\"",
        "    local ok, result = pcall(function() return io.open(re9_pose_logger.pose_log_file, \"w\") end)",
        "    if not ok or result == nil then",
        "        re9_pose_logger.logging = false",
        "        re9_pose_logger.last_error = \"Could not open pose log file: \" .. tostring(result)",
        "        re9_pose_write_status()",
        "        return",
        "    end",
        "    re9_pose_logger.file_handle = result",
        "    re9_pose_logger.file_handle:write(\"session_id,timestamp_sec,x,y,z,yaw,yaw_norm_rad,yaw_norm_deg,pitch,fov,freecam_mode,user_has_rotated\\n\")",
        "    re9_pose_logger.logging = true",
        "    re9_pose_write_status()",
        "end",
        "",
        "local function re9_pose_stop()",
        "    re9_pose_logger.logging = false",
        "    re9_pose_logger.scan_pose_enabled = false",
        "    re9_pose_logger.scan_segment_id = \"\"",
        "    re9_pose_logger.trajectory_enabled = false",
        "    re9_pose_logger.trajectory_id = \"\"",
        "    re9_pose_logger.trajectory_keyframes = nil",
        "    re9_pose_logger.trajectory_frame_count = 0",
        "    if re9_pose_logger.file_handle ~= nil then",
        "        pcall(function() re9_pose_logger.file_handle:flush(); re9_pose_logger.file_handle:close() end)",
        "        re9_pose_logger.file_handle = nil",
        "    end",
        "    re9_pose_write_status()",
        "end",
        "",
        "local function re9_pose_set_scan_pose(control)",
        "    if control == nil then return end",
        "    if not re9_pose_is_freecam_mode() or freecam_pos == nil then",
        "        re9_pose_logger.last_error = \"Enable FreeCam before running scan set_pose\"",
        "        re9_pose_write_status()",
        "        return",
        "    end",
        "    re9_pose_logger.scan_pose_enabled = true",
        "    re9_pose_logger.scan_segment_id = tostring(control.segment_id or \"\")",
        "    re9_pose_logger.scan_x = tonumber(control.x) or re9_pose_logger.scan_x",
        "    re9_pose_logger.scan_y = tonumber(control.y) or re9_pose_logger.scan_y",
        "    re9_pose_logger.scan_z = tonumber(control.z) or re9_pose_logger.scan_z",
        "    re9_pose_logger.scan_x_start = re9_pose_logger.scan_x",
        "    re9_pose_logger.scan_y_start = re9_pose_logger.scan_y",
        "    re9_pose_logger.scan_z_start = re9_pose_logger.scan_z",
        "    re9_pose_logger.scan_x_end = tonumber(control.x_end) or re9_pose_logger.scan_x",
        "    re9_pose_logger.scan_y_end = tonumber(control.y_end) or re9_pose_logger.scan_y",
        "    re9_pose_logger.scan_z_end = tonumber(control.z_end) or re9_pose_logger.scan_z",
        "    re9_pose_logger.scan_yaw = tonumber(control.yaw) or re9_pose_logger.scan_yaw",
        "    re9_pose_logger.scan_yaw_start = re9_pose_logger.scan_yaw",
        "    re9_pose_logger.scan_yaw_end = tonumber(control.yaw_end) or re9_pose_logger.scan_yaw",
        "    re9_pose_logger.scan_pitch = tonumber(control.pitch) or re9_pose_logger.scan_pitch",
        "    re9_pose_logger.scan_pitch_start = re9_pose_logger.scan_pitch",
        "    re9_pose_logger.scan_pitch_end = tonumber(control.pitch_end) or re9_pose_logger.scan_pitch",
        "    re9_pose_logger.scan_duration_sec = tonumber(control.duration_sec) or 0",
        "    re9_pose_logger.scan_start_clock = os.clock()",
        "    if control.fov ~= nil then re9_pose_logger.scan_fov = tonumber(control.fov) end",
        "    re9_pose_logger.scan_fov_start = re9_pose_logger.scan_fov",
        "    re9_pose_logger.scan_fov_end = tonumber(control.fov_end) or re9_pose_logger.scan_fov",
        "    re9_pose_logger.last_error = \"\"",
        "    re9_pose_write_status()",
        "end",
        "",
        "local function re9_pose_clear_scan_pose()",
        "    re9_pose_logger.scan_pose_enabled = false",
        "    re9_pose_logger.scan_segment_id = \"\"",
        "    re9_pose_logger.trajectory_enabled = false",
        "    re9_pose_logger.trajectory_id = \"\"",
        "    re9_pose_logger.trajectory_keyframes = nil",
        "    re9_pose_logger.trajectory_frame_count = 0",
        "    re9_pose_write_status()",
        "end",
        "",
        "local function re9_pose_set_trajectory(control)",
        "    if control == nil then return end",
        "    if not re9_pose_is_freecam_mode() or freecam_pos == nil then",
        "        re9_pose_logger.last_error = \"Enable FreeCam before running play_trajectory\"",
        "        re9_pose_write_status()",
        "        return",
        "    end",
        "    local frames = control.keyframes",
        "    if type(frames) ~= \"table\" or #frames < 2 then",
        "        re9_pose_logger.last_error = \"play_trajectory requires at least two keyframes and json.load_file support\"",
        "        re9_pose_write_status()",
        "        return",
        "    end",
        "    table.sort(frames, function(a, b) return (tonumber(a.time_sec) or 0) < (tonumber(b.time_sec) or 0) end)",
        "    for i, frame in ipairs(frames) do",
        "        frame.time_sec = tonumber(frame.time_sec) or ((i - 1) * 0.2)",
        "        frame.x = tonumber(frame.x) or 0",
        "        frame.y = tonumber(frame.y) or 0",
        "        frame.z = tonumber(frame.z) or 0",
        "        frame.yaw = tonumber(frame.yaw) or 0",
        "        frame.pitch = tonumber(frame.pitch) or 0",
        "        if frame.fov ~= nil then frame.fov = tonumber(frame.fov) end",
        "    end",
        "    re9_pose_logger.scan_pose_enabled = true",
        "    re9_pose_logger.scan_segment_id = tostring(control.trajectory_id or \"trajectory\")",
        "    re9_pose_logger.trajectory_enabled = true",
        "    re9_pose_logger.trajectory_id = tostring(control.trajectory_id or \"trajectory\")",
        "    re9_pose_logger.trajectory_keyframes = frames",
        "    re9_pose_logger.trajectory_start_clock = os.clock()",
        "    re9_pose_logger.trajectory_duration_sec = tonumber(frames[#frames].time_sec) or 0",
        "    re9_pose_logger.trajectory_frame_count = #frames",
        "    re9_pose_logger.last_error = \"\"",
        "    re9_pose_write_status()",
        "end",
        "",
        "local function re9_pose_apply_frame_pair(a, b, t)",
        "    if a == nil then return end",
        "    if b == nil then b = a end",
        "    if t < 0 then t = 0 end",
        "    if t > 1 then t = 1 end",
        "    freecam_pos.x = (tonumber(a.x) or 0) + ((tonumber(b.x) or tonumber(a.x) or 0) - (tonumber(a.x) or 0)) * t",
        "    freecam_pos.y = (tonumber(a.y) or 0) + ((tonumber(b.y) or tonumber(a.y) or 0) - (tonumber(a.y) or 0)) * t",
        "    freecam_pos.z = (tonumber(a.z) or 0) + ((tonumber(b.z) or tonumber(a.z) or 0) - (tonumber(a.z) or 0)) * t",
        "    freecam_yaw = (tonumber(a.yaw) or 0) + ((tonumber(b.yaw) or tonumber(a.yaw) or 0) - (tonumber(a.yaw) or 0)) * t",
        "    freecam_pitch = (tonumber(a.pitch) or 0) + ((tonumber(b.pitch) or tonumber(a.pitch) or 0) - (tonumber(a.pitch) or 0)) * t",
        "    if a.fov ~= nil and b.fov ~= nil then",
        "        global_fov = (tonumber(a.fov) or 0) + ((tonumber(b.fov) or tonumber(a.fov) or 0) - (tonumber(a.fov) or 0)) * t",
        "        use_custom_fov = true",
        "    end",
        "    user_has_rotated = true",
        "    yaw_pitch_initialized = true",
        "end",
        "",
        "local function re9_pose_apply_trajectory_pose()",
        "    if not re9_pose_logger.trajectory_enabled then return false end",
        "    if not re9_pose_is_freecam_mode() or freecam_pos == nil then return true end",
        "    local frames = re9_pose_logger.trajectory_keyframes",
        "    if type(frames) ~= \"table\" or #frames < 1 then return true end",
        "    local elapsed = os.clock() - (tonumber(re9_pose_logger.trajectory_start_clock) or os.clock())",
        "    if elapsed >= (tonumber(re9_pose_logger.trajectory_duration_sec) or 0) then",
        "        re9_pose_apply_frame_pair(frames[#frames], frames[#frames], 1)",
        "        re9_pose_logger.trajectory_enabled = false",
        "        re9_pose_logger.scan_pose_enabled = false",
        "        return true",
        "    end",
        "    local previous = frames[1]",
        "    for i = 2, #frames do",
        "        local current = frames[i]",
        "        local a_time = tonumber(previous.time_sec) or 0",
        "        local b_time = tonumber(current.time_sec) or a_time",
        "        if elapsed <= b_time then",
        "            local span = b_time - a_time",
        "            local t = 1",
        "            if span > 0 then t = (elapsed - a_time) / span end",
        "            re9_pose_apply_frame_pair(previous, current, t)",
        "            return true",
        "        end",
        "        previous = current",
        "    end",
        "    re9_pose_apply_frame_pair(frames[#frames], frames[#frames], 1)",
        "    return true",
        "end",
        "",
        "local function re9_pose_apply_scan_pose()",
        "    if not re9_pose_logger.scan_pose_enabled then return end",
        "    if not re9_pose_is_freecam_mode() or freecam_pos == nil then return end",
        "    if re9_pose_apply_trajectory_pose() then return end",
        "    local t = 1",
        "    if re9_pose_logger.scan_duration_sec ~= nil and re9_pose_logger.scan_duration_sec > 0 then",
        "        t = (os.clock() - re9_pose_logger.scan_start_clock) / re9_pose_logger.scan_duration_sec",
        "        if t < 0 then t = 0 end",
        "        if t > 1 then t = 1 end",
        "    end",
        "    freecam_pos.x = re9_pose_logger.scan_x_start + (re9_pose_logger.scan_x_end - re9_pose_logger.scan_x_start) * t",
        "    freecam_pos.y = re9_pose_logger.scan_y_start + (re9_pose_logger.scan_y_end - re9_pose_logger.scan_y_start) * t",
        "    freecam_pos.z = re9_pose_logger.scan_z_start + (re9_pose_logger.scan_z_end - re9_pose_logger.scan_z_start) * t",
        "    local yaw_value = re9_pose_logger.scan_yaw",
        "    yaw_value = re9_pose_logger.scan_yaw_start + (re9_pose_logger.scan_yaw_end - re9_pose_logger.scan_yaw_start) * t",
        "    re9_pose_logger.scan_yaw = yaw_value",
        "    freecam_yaw = yaw_value",
        "    freecam_pitch = re9_pose_logger.scan_pitch_start + (re9_pose_logger.scan_pitch_end - re9_pose_logger.scan_pitch_start) * t",
        "    if re9_pose_logger.scan_fov_start ~= nil and re9_pose_logger.scan_fov_end ~= nil then",
        "        global_fov = re9_pose_logger.scan_fov_start + (re9_pose_logger.scan_fov_end - re9_pose_logger.scan_fov_start) * t",
        "        use_custom_fov = true",
        "    end",
        "    user_has_rotated = true",
        "    yaw_pitch_initialized = true",
        "end",
        "",
        "local function re9_pose_write_scan_camera()",
        "    if not re9_pose_logger.scan_pose_enabled and not re9_pose_logger.trajectory_enabled then return end",
        "    if not re9_pose_is_freecam_mode() or freecam_pos == nil then return end",
        "    re9_pose_apply_scan_pose()",
        "    if type(write_yawpitch_matrix) == \"function\" then",
        "        pcall(function() write_yawpitch_matrix(freecam_pos.x, freecam_pos.y, freecam_pos.z, freecam_yaw, freecam_pitch) end)",
        "    end",
        "end",
        "",
        "local function re9_pose_get_number(name, fallback)",
        "    local value = _G[name]",
        "    if type(value) == \"number\" then return value end",
        "    return fallback or 0",
        "end",
        "",
        "re9_pose_get_pose = function()",
        "    local pos = nil",
        "    if type(freecam_pos) ~= \"nil\" then pos = freecam_pos end",
        "    if pos == nil and type(camera_pos) ~= \"nil\" then pos = camera_pos end",
        "    if pos == nil then return nil end",
        "    local x = pos.x or pos[1] or 0",
        "    local y = pos.y or pos[2] or 0",
        "    local z = pos.z or pos[3] or 0",
        "    local yaw_value = 0",
        "    local pitch_value = 0",
        "    local fov_value = 0",
        "    if type(freecam_yaw) ~= \"nil\" then yaw_value = freecam_yaw elseif type(yaw) ~= \"nil\" then yaw_value = yaw else yaw_value = re9_pose_get_number(\"yaw\", 0) end",
        "    if type(freecam_pitch) ~= \"nil\" then pitch_value = freecam_pitch elseif type(pitch) ~= \"nil\" then pitch_value = pitch else pitch_value = re9_pose_get_number(\"pitch\", 0) end",
        "    if type(global_fov) ~= \"nil\" then fov_value = global_fov elseif type(fov) ~= \"nil\" then fov_value = fov else fov_value = re9_pose_get_number(\"fov\", 0) end",
        "    return x, y, z, yaw_value, pitch_value, fov_value",
        "end",
        "",
        "function re9_pose_is_freecam_mode()",
        "    if type(freecam_mode) ~= \"nil\" then return freecam_mode == true end",
        "    if type(is_freecam) ~= \"nil\" then return is_freecam == true end",
        "    if type(enabled) ~= \"nil\" then return enabled == true end",
        "    return false",
        "end",
        "",
        "local function re9_pose_log_sample()",
        "    if not re9_pose_logger.enabled or not re9_pose_logger.logging then return end",
        "    if not re9_pose_is_freecam_mode() then return end",
        "    local x, y, z, yaw_value, pitch_value, fov_value = re9_pose_get_pose()",
        "    if x == nil then return end",
        "    local now = os.clock()",
        "    if re9_pose_logger.last_sample_clock ~= 0 and (now - re9_pose_logger.last_sample_clock) < re9_pose_logger.interval_sec then return end",
        "    re9_pose_logger.last_sample_clock = now",
        "    local timestamp_sec = now - re9_pose_logger.session_start_clock",
        "    local rotated = false",
        "    if type(user_has_rotated) ~= \"nil\" then rotated = user_has_rotated == true end",
        "    local yaw_norm_rad = yaw_value % (math.pi * 2)",
        "    if yaw_norm_rad < 0 then yaw_norm_rad = yaw_norm_rad + (math.pi * 2) end",
        "    local yaw_norm_deg = math.deg(yaw_norm_rad)",
        "    local ok, err = pcall(function()",
        "        re9_pose_logger.file_handle:write(string.format(\"%s,%.6f,%.9f,%.9f,%.9f,%.9f,%.9f,%.6f,%.9f,%.9f,%s,%s\\n\",",
        "            re9_pose_logger.session_id, timestamp_sec, x, y, z, yaw_value, yaw_norm_rad, yaw_norm_deg, pitch_value, fov_value,",
        "            tostring(re9_pose_is_freecam_mode()), tostring(rotated)))",
        "        re9_pose_logger.rows_written = re9_pose_logger.rows_written + 1",
        "        if re9_pose_logger.rows_written % 30 == 0 then re9_pose_logger.file_handle:flush(); re9_pose_write_status() end",
        "    end)",
        "    if not ok then re9_pose_logger.last_error = tostring(err); re9_pose_write_status() end",
        "end",
        "",
        "local function re9_pose_write_new_scene_json()",
        "    local csv_path = re9_pose_data_path(re9_pose_logger.new_scene_points_file)",
        "    local json_path = re9_pose_data_path(re9_pose_logger.new_scene_points_json_file)",
        "    local f = io.open(csv_path, \"r\")",
        "    if f == nil then return end",
        "    local rows = {}",
        "    local header = f:read(\"*l\")",
        "    local line = f:read(\"*l\")",
        "    while line ~= nil do",
        "        local index, x, y, z, yaw, pitch, fov = line:match('([^,]+),[^,]+,([^,]+),([^,]+),([^,]+),([^,]+),([^,]+),([^,]+)')",
        "        if index ~= nil then",
        "            table.insert(rows, string.format('{\"index\":%d,\"x\":%.9f,\"y\":%.9f,\"z\":%.9f,\"yaw\":%.9f,\"pitch\":%.9f,\"fov\":%.9f}',",
        "                tonumber(index) or 0, tonumber(x) or 0, tonumber(y) or 0, tonumber(z) or 0, tonumber(yaw) or 0, tonumber(pitch) or 0, tonumber(fov) or 0))",
        "        end",
        "        line = f:read(\"*l\")",
        "    end",
        "    f:close()",
        "    local out = io.open(json_path, \"w\")",
        "    if out ~= nil then",
        "        out:write('{\"scene\":\"new_scene\",\"points\":[' .. table.concat(rows, \",\") .. ']}')",
        "        out:close()",
        "    end",
        "end",
        "",
        "local function re9_pose_capture_new_scene_point()",
        "    if not re9_pose_is_freecam_mode() then",
        "        re9_pose_logger.last_error = \"Enable FreeCam before capturing a new scene point\"",
        "        re9_pose_write_status()",
        "        return",
        "    end",
        "    local x, y, z, yaw_value, pitch_value, fov_value = re9_pose_get_pose()",
        "    if x == nil then",
        "        re9_pose_logger.last_error = \"No FreeCam pose is available to capture\"",
        "        re9_pose_write_status()",
        "        return",
        "    end",
        "    local count = (tonumber(re9_pose_logger.new_scene_point_count) or 0) + 1",
        "    local csv_path = re9_pose_data_path(re9_pose_logger.new_scene_points_file)",
        "    local exists = false",
        "    local check = io.open(csv_path, \"r\")",
        "    if check ~= nil then exists = true; check:close() end",
        "    local f = io.open(csv_path, \"a\")",
        "    if f == nil then",
        "        re9_pose_logger.last_error = \"Could not open new scene points file\"",
        "        re9_pose_write_status()",
        "        return",
        "    end",
        "    if not exists then f:write(\"index,timestamp_sec,x,y,z,yaw,pitch,fov\\n\") end",
        "    f:write(string.format(\"%d,%.6f,%.9f,%.9f,%.9f,%.9f,%.9f,%.9f\\n\", count, os.clock(), x, y, z, yaw_value, pitch_value, fov_value))",
        "    f:close()",
        "    re9_pose_logger.new_scene_point_count = count",
        "    re9_pose_logger.new_scene_last_point = string.format(\"%02d x=%.2f y=%.2f z=%.2f\", count, x, y, z)",
        "    re9_pose_logger.last_error = \"\"",
        "    pcall(re9_pose_write_new_scene_json)",
        "    re9_pose_write_status()",
        "end",
        "",
        "local function re9_pose_reset_new_scene_points()",
        "    local csv_path = re9_pose_data_path(re9_pose_logger.new_scene_points_file)",
        "    local json_path = re9_pose_data_path(re9_pose_logger.new_scene_points_json_file)",
        "    local f = io.open(csv_path, \"w\")",
        "    if f ~= nil then f:write(\"index,timestamp_sec,x,y,z,yaw,pitch,fov\\n\"); f:close() end",
        "    local out = io.open(json_path, \"w\")",
        "    if out ~= nil then out:write('{\"scene\":\"new_scene\",\"points\":[]}'); out:close() end",
        "    re9_pose_logger.new_scene_point_count = 0",
        "    re9_pose_logger.new_scene_last_point = \"\"",
        "    re9_pose_logger.last_error = \"\"",
        "    re9_pose_write_status()",
        "end",
        "",
        "local function re9_pose_poll_control()",
        "    local now = os.clock()",
        "    if (now - re9_pose_logger.last_control_clock) < 0.25 then return end",
        "    re9_pose_logger.last_control_clock = now",
        "    local control = re9_pose_read_control()",
        "    if control == nil or control.command == nil then return end",
        "    local command_id = tostring(control.command_id or control.command or \"\")",
        "    if command_id ~= \"\" and command_id == re9_pose_logger.last_command_id then return end",
        "    re9_pose_logger.last_command_id = command_id",
        "    if control.command == \"start\" and control.session_id ~= re9_pose_logger.session_id then",
        "        re9_pose_start(control.session_id, control.pose_log_file, control.interval_sec)",
        "    elseif control.command == \"stop\" and control.session_id == re9_pose_logger.session_id then",
        "        re9_pose_stop()",
        "    elseif control.command == \"set_pose\" then",
        "        re9_pose_set_scan_pose(control)",
        "    elseif control.command == \"play_trajectory\" then",
        "        re9_pose_set_trajectory(control)",
        "    elseif control.command == \"clear_pose\" then",
        "        re9_pose_clear_scan_pose()",
        "    elseif control.command == \"physics_probe\" then",
        "        re9_pose_run_physics_probe()",
        "    end",
        "end",
        "",
        "re.on_pre_application_entry(\"LateUpdateBehavior\", function()",
        "    pcall(re9_pose_apply_scan_pose)",
        "end)",
        "",
        "re.on_pre_application_entry(\"LockScene\", function()",
        "    pcall(re9_pose_write_scan_camera)",
        "end)",
        "",
        "re.on_frame(function()",
        "    pcall(re9_pose_poll_control)",
        "    pcall(re9_pose_apply_scan_pose)",
        "    pcall(re9_pose_log_sample)",
        "end)",
        "",
        "re.on_draw_ui(function()",
        "    if imgui.tree_node(\"RE9 Aesthetic Pose Logger\") then",
        "        changed, re9_pose_logger.enabled = imgui.checkbox(\"Pose Logging Enabled\", re9_pose_logger.enabled)",
        "        changed, re9_pose_logger.interval_sec = imgui.slider_float(\"Logging Interval\", re9_pose_logger.interval_sec, 0.005, 1.0)",
        "        if imgui.button(\"Start Pose Log\") then re9_pose_start(os.date(\"%Y%m%d_%H%M%S\"), re9_pose_logger.pose_log_file, re9_pose_logger.interval_sec) end",
        "        imgui.same_line()",
        "        if imgui.button(\"Stop Pose Log\") then re9_pose_stop() end",
        "        imgui.text(\"Logger status: \" .. tostring(re9_pose_logger.logging))",
        "        imgui.text(\"Session id: \" .. tostring(re9_pose_logger.session_id))",
        "        imgui.text(\"Rows written: \" .. tostring(re9_pose_logger.rows_written))",
        "        imgui.text(\"Pose log file: \" .. tostring(re9_pose_logger.pose_log_file))",
        "        imgui.text(\"New scene points: \" .. tostring(re9_pose_logger.new_scene_point_count) .. \"/8\")",
        "        if imgui.button(\"Capture New Scene Point\") then re9_pose_capture_new_scene_point() end",
        "        imgui.same_line()",
        "        if imgui.button(\"Reset New Scene Points\") then re9_pose_reset_new_scene_points() end",
        "        if re9_pose_logger.new_scene_last_point ~= \"\" then imgui.text(\"Last new scene point: \" .. tostring(re9_pose_logger.new_scene_last_point)) end",
        "        imgui.text(\"New scene file: \" .. tostring(re9_pose_logger.new_scene_points_file))",
        "        imgui.text(\"Scan pose enabled: \" .. tostring(re9_pose_logger.scan_pose_enabled))",
        "        imgui.text(\"Scan segment id: \" .. tostring(re9_pose_logger.scan_segment_id))",
        "        changed, re9_pose_logger.physics_clip_distance = imgui.slider_float(\"Physics Clip Distance\", re9_pose_logger.physics_clip_distance, 0.005, 0.2)",
        "        changed, re9_pose_logger.physics_near_distance = imgui.slider_float(\"Physics Near Distance\", re9_pose_logger.physics_near_distance, 0.02, 0.5)",
        "        changed, re9_pose_logger.physics_sphere_radius = imgui.slider_float(\"Physics Sphere Radius\", re9_pose_logger.physics_sphere_radius, 0.01, 0.3)",
        "        changed, re9_pose_logger.physics_filter_layer = imgui.slider_float(\"Physics Filter Layer\", re9_pose_logger.physics_filter_layer, 0, 31)",
        "        changed, re9_pose_logger.physics_filter_mask_bit = imgui.slider_float(\"Physics Mask Bit\", re9_pose_logger.physics_filter_mask_bit, 0, 31)",
        "        changed, re9_pose_logger.physics_saturation_invalid = imgui.checkbox(\"Treat Saturated Probe As Invalid\", re9_pose_logger.physics_saturation_invalid)",
        "        if imgui.button(\"Test Physics Probe\") then re9_pose_run_physics_probe() end",
        "        imgui.same_line()",
        "        if imgui.button(\"Scan Physics Filter Bits\") then re9_pose_scan_physics_filter_bits() end",
        "        if imgui.button(\"Probe Camera Collision\") then re9_pose_probe_camera_collision_system() end",
        "        imgui.text(\"Physics probe: \" .. tostring(re9_pose_logger.physics_probe_status) .. \" valid=\" .. tostring(re9_pose_logger.physics_probe_pose_valid) .. \" hit_dirs=\" .. tostring(re9_pose_logger.physics_probe_contacts) .. \"/\" .. tostring(re9_pose_logger.physics_probe_rays))",
        "        if re9_pose_logger.physics_probe_details ~= \"\" then imgui.text(\"Physics details: \" .. tostring(re9_pose_logger.physics_probe_details)) end",
        "        if re9_pose_logger.physics_probe_error ~= \"\" then imgui.text(\"Physics error: \" .. tostring(re9_pose_logger.physics_probe_error)) end",
        "        if re9_pose_logger.last_error ~= \"\" then imgui.text(\"Last error: \" .. tostring(re9_pose_logger.last_error)) end",
        "        imgui.tree_pop()",
        "    end",
        "end)",
        END_MARKER,
    ]
    return newline.join(lines) + newline


def _replace_or_append_block(text: str, block: str, newline: str) -> str:
    if BEGIN_MARKER in text or END_MARKER in text:
        start = text.find(BEGIN_MARKER)
        end = text.find(END_MARKER)
        if start == -1 or end == -1 or end < start:
            raise RuntimeError("Lua patch markers are malformed; restore from backup or repair markers before patching.")
        end += len(END_MARKER)
        while end < len(text) and text[end] in "\r\n":
            end += 1
        return text[:start] + block + text[end:]
    spacer = "" if text.endswith(("\n", "\r")) else newline
    return text + spacer + newline + block


def _read_text_preserving(path: Path) -> tuple[str, str]:
    data = path.read_bytes()
    try:
        text = data.decode("utf-8-sig")
    except UnicodeDecodeError:
        text = data.decode("cp1252")
    crlf = text.count("\r\n")
    lf = text.count("\n") - crlf
    newline = "\r\n" if crlf >= lf else "\n"
    return text, newline
